
-- Sistema de Impulsionar Equipe
alter table public.affiliate_settings
  add column if not exists team_boost_small_price numeric(12,2) not null default 30.00,
  add column if not exists team_boost_small_connections integer not null default 5,
  add column if not exists team_boost_large_price numeric(12,2) not null default 50.00,
  add column if not exists team_boost_large_connections integer not null default 10,
  add column if not exists team_boost_max_active integer not null default 3;

alter table public.affiliates
  add column if not exists team_join_source text;

update public.affiliates
set team_join_source = 'organic'
where team_parent_id is not null and (team_join_source is null or team_join_source = '');

alter table public.affiliates
  drop constraint if exists affiliates_team_join_source_check;
alter table public.affiliates
  add constraint affiliates_team_join_source_check
  check (team_join_source is null or team_join_source in ('organic', 'boost'));

create table if not exists public.affiliate_team_boosts (
  id bigint generated by default as identity primary key,
  affiliate_id bigint not null references public.affiliates(id) on delete cascade,
  price numeric(12,2) not null check (price > 0),
  connections_total integer not null check (connections_total > 0),
  connections_remaining integer not null check (connections_remaining >= 0),
  status text not null default 'queued' check (status in ('queued','active','completed','cancelled')),
  queue_created_at timestamptz not null default now(),
  activated_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists affiliate_team_boosts_status_queue_idx
  on public.affiliate_team_boosts(status, queue_created_at asc);
create index if not exists affiliate_team_boosts_affiliate_idx
  on public.affiliate_team_boosts(affiliate_id, created_at desc);
alter table public.affiliate_team_boosts enable row level security;

create sequence if not exists public.team_boost_activation_seq;

alter table public.affiliate_team_boosts
  add column if not exists activation_order bigint;

create unique index if not exists affiliate_team_boosts_one_open_per_affiliate_idx
  on public.affiliate_team_boosts(affiliate_id)
  where status in ('queued','active');

create table if not exists public.affiliate_team_boost_reservations (
  id bigint generated by default as identity primary key,
  boost_id bigint not null references public.affiliate_team_boosts(id) on delete cascade,
  affiliate_id bigint not null references public.affiliates(id) on delete cascade,
  status text not null default 'reserved' check (status in ('reserved','consumed','expired')),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  consumed_at timestamptz
);

create index if not exists affiliate_team_boost_reservations_boost_idx
  on public.affiliate_team_boost_reservations(boost_id, status, expires_at);
create unique index if not exists affiliate_team_boost_reservations_one_open_per_affiliate_idx
  on public.affiliate_team_boost_reservations(affiliate_id)
  where status = 'reserved';
alter table public.affiliate_team_boost_reservations enable row level security;

create table if not exists public.team_boost_distribution_state (
  id integer primary key check (id = 1),
  last_boost_id bigint references public.affiliate_team_boosts(id) on delete set null,
  updated_at timestamptz not null default now()
);
insert into public.team_boost_distribution_state (id)
values (1)
on conflict (id) do nothing;
alter table public.team_boost_distribution_state enable row level security;

create or replace function public.she_team_boost_activate_waiting()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  max_active integer;
  active_count integer;
  next_boost record;
begin
  select team_boost_max_active into max_active from affiliate_settings where id = 1;
  max_active := greatest(coalesce(max_active, 3), 0);

  loop
    select count(*) into active_count from affiliate_team_boosts where status = 'active';
    exit when active_count >= max_active;

    select * into next_boost
    from affiliate_team_boosts
    where status = 'queued'
    order by queue_created_at asc, id asc
    limit 1
    for update skip locked;

    exit when not found;

    update affiliate_team_boosts
    set status = 'active', activated_at = now(), activation_order = nextval('team_boost_activation_seq')
    where id = next_boost.id;
  end loop;
end;
$$;

create or replace function public.she_team_boost_purchase(
  p_affiliate_id bigint,
  p_price numeric,
  p_connections integer,
  p_earned_balance numeric
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  existing record;
  reserved_amount numeric;
  personal_withdrawals numeric;
  available numeric;
  new_boost record;
begin
  perform pg_advisory_xact_lock(984512, p_affiliate_id::integer);

  select * into existing
  from affiliate_team_boosts
  where affiliate_id = p_affiliate_id and status in ('queued','active')
  limit 1;
  if found then
    raise exception 'Você já possui um impulso na fila ou ativo.' using errcode = 'P0001';
  end if;

  select coalesce(sum(amount),0) into personal_withdrawals
  from affiliate_withdrawals
  where affiliate_id = p_affiliate_id and source = 'personal' and status in ('pending','approved','paid');

  select coalesce(sum(price),0) into reserved_amount
  from affiliate_team_boosts
  where affiliate_id = p_affiliate_id and status in ('queued','active','completed');

  available := coalesce(p_earned_balance,0) - personal_withdrawals - reserved_amount;
  if available + 0.001 < p_price then
    raise exception 'Saldo disponível insuficiente para este impulso. Saldo: R$ %', round(available,2) using errcode = 'P0002';
  end if;

  insert into affiliate_team_boosts (affiliate_id, price, connections_total, connections_remaining, status)
  values (p_affiliate_id, p_price, p_connections, p_connections, 'queued')
  returning * into new_boost;

  perform she_team_boost_activate_waiting();

  select * into new_boost from affiliate_team_boosts where id = new_boost.id;
  return jsonb_build_object('boostId', new_boost.id, 'status', new_boost.status, 'price', new_boost.price, 'connections', new_boost.connections_total);
end;
$$;

create or replace function public.she_team_boost_find(p_affiliate_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  existing_reservation record;
  selected_boost record;
  state_last bigint;
  expiry timestamptz := now() + interval '15 minutes';
  reserved_count integer;
begin
  perform pg_advisory_xact_lock(984513, p_affiliate_id::integer);

  update affiliate_team_boost_reservations
  set status = 'expired'
  where status = 'reserved' and expires_at <= now();

  select * into existing_reservation
  from affiliate_team_boost_reservations
  where affiliate_id = p_affiliate_id and status = 'reserved' and expires_at > now()
  order by id desc limit 1;

  if found then
    select b.*, a.name as parent_name
    into selected_boost
    from affiliate_team_boosts b join affiliates a on a.id = b.affiliate_id
    where b.id = existing_reservation.boost_id;
    return jsonb_build_object('reservationId', existing_reservation.id, 'parentId', selected_boost.affiliate_id, 'parentName', selected_boost.parent_name, 'expiresAt', existing_reservation.expires_at);
  end if;

  perform she_team_boost_activate_waiting();

  select last_boost_id into state_last from team_boost_distribution_state where id = 1 for update;

  if state_last is null then
    select b.*, a.name as parent_name into selected_boost
    from affiliate_team_boosts b join affiliates a on a.id = b.affiliate_id
    where b.status = 'active' and b.connections_remaining > 0
      and not exists (select 1 from affiliate_team_boost_reservations r where r.boost_id=b.id and r.status='reserved' and r.expires_at>now())
    order by b.activation_order asc nulls first, b.id asc limit 1;
  else
    select b.*, a.name as parent_name into selected_boost
    from affiliate_team_boosts b join affiliates a on a.id = b.affiliate_id
    where b.status = 'active' and b.connections_remaining > 0
      and not exists (select 1 from affiliate_team_boost_reservations r where r.boost_id=b.id and r.status='reserved' and r.expires_at>now())
      and b.activation_order > (select coalesce(activation_order,0) from affiliate_team_boosts where id=state_last)
    order by b.activation_order asc limit 1;

    if not found then
      select b.*, a.name as parent_name into selected_boost
      from affiliate_team_boosts b join affiliates a on a.id = b.affiliate_id
      where b.status = 'active' and b.connections_remaining > 0
        and not exists (select 1 from affiliate_team_boost_reservations r where r.boost_id=b.id and r.status='reserved' and r.expires_at>now())
      order by b.activation_order asc nulls first, b.id asc limit 1;
    end if;
  end if;

  if not found then
    raise exception 'No momento não há uma conexão disponível para encontrar equipe.' using errcode='P0003';
  end if;

  insert into affiliate_team_boost_reservations (boost_id, affiliate_id, expires_at)
  values (selected_boost.id, p_affiliate_id, expiry)
  returning id into existing_reservation;

  update team_boost_distribution_state set last_boost_id=selected_boost.id, updated_at=now() where id=1;

  return jsonb_build_object('reservationId', existing_reservation.id, 'parentId', selected_boost.affiliate_id, 'parentName', selected_boost.parent_name, 'expiresAt', expiry);
end;
$$;

create or replace function public.she_team_boost_confirm(
  p_affiliate_id bigint,
  p_reservation_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  reservation record;
  boost record;
  child record;
  parent record;
  remaining integer;
begin
  perform pg_advisory_xact_lock(984514, p_affiliate_id::integer);

  select * into reservation from affiliate_team_boost_reservations
  where id=p_reservation_id and affiliate_id=p_affiliate_id and status='reserved'
  for update;
  if not found or reservation.expires_at <= now() then
    if found then update affiliate_team_boost_reservations set status='expired' where id=reservation.id; end if;
    raise exception 'A indicação de equipe expirou. Encontre uma nova equipe.' using errcode='P0004';
  end if;

  select * into child from affiliates where id=p_affiliate_id for update;
  if child.team_parent_id is not null then raise exception 'Você já está em uma equipe.' using errcode='P0005'; end if;
  if exists (select 1 from affiliate_orders where affiliate_id=p_affiliate_id and lower(status) in ('payment_approved','paid','pagamento_aprovado')) then
    raise exception 'A entrada em uma equipe só pode ser feita antes da primeira venda.' using errcode='P0006';
  end if;

  select * into boost from affiliate_team_boosts where id=reservation.boost_id for update;
  if boost.status <> 'active' or boost.connections_remaining <= 0 then raise exception 'Essa conexão não está mais disponível.' using errcode='P0007'; end if;

  select * into parent from affiliates where id=boost.affiliate_id and active=true;
  if not found then raise exception 'A afiliada mãe não está disponível.' using errcode='P0008'; end if;

  update affiliates set team_parent_id=parent.id, team_joined_at=now(), team_join_source='boost' where id=p_affiliate_id;
  update affiliate_team_boost_reservations set status='consumed', consumed_at=now() where id=reservation.id;
  remaining := boost.connections_remaining - 1;
  update affiliate_team_boosts
  set connections_remaining=remaining,
      status=case when remaining=0 then 'completed' else status end,
      completed_at=case when remaining=0 then now() else completed_at end
  where id=boost.id;

  if remaining=0 then perform she_team_boost_activate_waiting(); end if;

  return jsonb_build_object('affiliateId',p_affiliate_id,'parentId',parent.id,'parentName',parent.name,'parentWhatsapp',coalesce(parent.whatsapp,''),'boostId',boost.id,'connectionsRemaining',remaining);
end;
$$;

create or replace function public.she_team_boost_leave_queue(p_affiliate_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  boost record;
begin
  perform pg_advisory_xact_lock(984515, p_affiliate_id::integer);
  select * into boost from affiliate_team_boosts where affiliate_id=p_affiliate_id and status='queued' order by id desc limit 1 for update;
  if not found then raise exception 'Você não possui um impulso aguardando na fila.' using errcode='P0009'; end if;
  update affiliate_team_boosts set status='cancelled', completed_at=now() where id=boost.id;
  return jsonb_build_object('boostId',boost.id,'refunded',boost.price);
end;
$$;

create or replace function public.she_team_boost_admin_state()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  active_count integer;
  queue_count integer;
  delivered integer;
  active_rows jsonb;
begin
  select count(*) into active_count from affiliate_team_boosts where status='active';
  select count(*) into queue_count from affiliate_team_boosts where status='queued';
  select count(*) into delivered from affiliate_team_boosts where status='completed';
  select coalesce(jsonb_agg(x order by x.activated_at asc), '[]'::jsonb) into active_rows
  from (
    select b.id,b.affiliate_id,a.name,a.whatsapp,b.price,b.connections_total,b.connections_remaining,b.status,b.queue_created_at,b.activated_at
    from affiliate_team_boosts b join affiliates a on a.id=b.affiliate_id
    where b.status='active'
    order by b.activated_at asc
  ) x;
  return jsonb_build_object('activeCount',active_count,'queueCount',queue_count,'completedCount',delivered,'active',active_rows);
end;
$$;

