create table if not exists public.affiliate_password_reset_tokens (
  id bigint generated by default as identity primary key,
  affiliate_id bigint not null references public.affiliates(id) on delete cascade,
  token_hash text not null unique,
  expires_at timestamptz not null,
  used_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists affiliate_password_reset_tokens_affiliate_idx
  on public.affiliate_password_reset_tokens(affiliate_id, created_at desc);
create index if not exists affiliate_password_reset_tokens_expiry_idx
  on public.affiliate_password_reset_tokens(expires_at);
alter table public.affiliate_password_reset_tokens enable row level security;

-- Controle de duplicidade dos alertas de nova venda enviados por WhatsApp.
-- O mesmo pedido pode chegar pelo webhook da Yampi e pela sincronização manual.
alter table public.affiliate_orders
  add column if not exists whatsapp_personal_sale_notified_at timestamptz,
  add column if not exists whatsapp_team_sale_notified_at timestamptz;
