-- SHE AFILIADAS — integração de pagamentos Pix de saques via Woovi
-- Execute no Supabase SQL Editor antes de publicar o código.

alter table public.affiliate_withdrawals
  add column if not exists woovi_payment_id text,
  add column if not exists woovi_correlation_id text,
  add column if not exists woovi_status text,
  add column if not exists woovi_fail_reason text,
  add column if not exists woovi_end_to_end_id text;

create unique index if not exists affiliate_withdrawals_woovi_correlation_unique_idx
  on public.affiliate_withdrawals(woovi_correlation_id)
  where woovi_correlation_id is not null;

create unique index if not exists affiliate_withdrawals_woovi_payment_unique_idx
  on public.affiliate_withdrawals(woovi_payment_id)
  where woovi_payment_id is not null;

create table if not exists public.woovi_webhook_events (
  id bigint generated by default as identity primary key,
  woovi_event_id text not null unique,
  event_type text,
  correlation_id text,
  payment_id text,
  payload jsonb,
  received_at timestamptz not null default now()
);

create index if not exists woovi_webhook_events_correlation_idx
  on public.woovi_webhook_events(correlation_id);

alter table public.woovi_webhook_events enable row level security;
