-- SHE AFILIADAS — integração de saques automáticos via Asaas
-- Execute no Supabase SQL Editor antes de publicar a nova versão.

alter table public.affiliate_withdrawals
  drop constraint if exists affiliate_withdrawals_status_check;

alter table public.affiliate_withdrawals
  add constraint affiliate_withdrawals_status_check
  check (status in ('pending','approved','processing','paid','failed','rejected','cancelled'));

alter table public.affiliates
  add column if not exists pix_key_type text;

alter table public.affiliate_withdrawals
  add column if not exists pix_key_type text,
  add column if not exists asaas_transfer_id text,
  add column if not exists asaas_status text,
  add column if not exists asaas_fail_reason text,
  add column if not exists transaction_receipt_url text;

create unique index if not exists affiliate_withdrawals_asaas_transfer_unique_idx
  on public.affiliate_withdrawals(asaas_transfer_id)
  where asaas_transfer_id is not null;

create index if not exists affiliate_withdrawals_status_idx
  on public.affiliate_withdrawals(status, requested_at desc);

create table if not exists public.asaas_webhook_events (
  id bigint generated by default as identity primary key,
  asaas_event_id text not null unique,
  event_type text,
  transfer_id text,
  payload jsonb,
  received_at timestamptz not null default now()
);

create index if not exists asaas_webhook_events_transfer_idx
  on public.asaas_webhook_events(transfer_id);

alter table public.asaas_webhook_events enable row level security;

-- Migra a chave Pix existente para CPF somente quando ela tiver formato de CPF.
update public.affiliate_withdrawals
set pix_key_type = 'CPF'
where pix_key_type is null
  and pix_key ~ '^[0-9]{11}$';

-- As novas solicitações devem receber o tipo de chave informado pela afiliada.
