-- SHE AFILIADAS
-- Execute este SQL no Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.affiliates (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique,
  name text not null,
  slug text not null unique,
  email text not null unique,
  cpf text,
  whatsapp text,
  pix_key text,
  active boolean not null default true,
  commission_rate numeric(6,4) not null default 0.1000,
  created_at timestamptz not null default now()
);

create table if not exists public.affiliate_events (
  id bigint generated by default as identity primary key,
  affiliate_id bigint not null references public.affiliates(id) on delete cascade,
  type text not null check (type in ('access','click')),
  target text,
  visitor_id text,
  path text,
  referrer text,
  event_key text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.affiliate_orders (
  id bigint generated by default as identity primary key,
  yampi_order_id text not null unique,
  affiliate_id bigint not null references public.affiliates(id) on delete cascade,
  status text not null default 'created',
  total numeric(12,2) not null default 0,
  commission numeric(12,2) not null default 0,
  raw_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists affiliate_events_affiliate_idx on public.affiliate_events(affiliate_id, created_at desc);
create index if not exists affiliate_orders_affiliate_idx on public.affiliate_orders(affiliate_id, created_at desc);
create index if not exists affiliate_orders_status_idx on public.affiliate_orders(status);

alter table public.affiliates enable row level security;
alter table public.affiliate_events enable row level security;
-- Commission history is locked per order. A level upgrade can rewrite prior
-- orders in that same month, but changing admin values alone never rewrites history.
alter table public.affiliate_orders
  add column if not exists commission_rate_locked numeric(12,2);
alter table public.affiliate_orders
  add column if not exists commission_level_key text;
alter table public.affiliate_orders
  add column if not exists team_commission_locked numeric(12,2);


-- One-time historical freeze for orders that already existed before commission
-- locking was introduced. The values are derived from the current rules once;
-- future admin changes do not rewrite these rows.
do $$
declare
  settings_row record;
begin
  select ticket_threshold, ticket_bonus, team_commission_per_sale,
         commission_none, commission_bronze, commission_silver, commission_gold
    into settings_row
    from public.affiliate_settings
   where id = 1;

  if settings_row is not null then
    with paid as (
      select o.id,
             o.affiliate_id,
             date_trunc('month', o.created_at) as month_start,
             count(*) over (partition by o.affiliate_id, date_trunc('month', o.created_at)) as month_sales
        from public.affiliate_orders o
       where lower(o.status) in ('payment_approved','paid','pagamento_aprovado')
    ), rates as (
      select p.id,
             case
               when p.month_sales >= 101 then 'gold'
               when p.month_sales >= 50 then 'silver'
               when p.month_sales >= 10 then 'bronze'
               else 'none'
             end as level_key,
             case
               when p.month_sales >= 101 then settings_row.commission_gold
               when p.month_sales >= 50 then settings_row.commission_silver
               when p.month_sales >= 10 then settings_row.commission_bronze
               else settings_row.commission_none
             end as rate
        from paid p
    )
    update public.affiliate_orders o
       set commission_level_key = r.level_key,
           commission_rate_locked = r.rate
      from rates r
     where o.id = r.id
       and o.commission_rate_locked is null;

    update public.affiliate_orders o
       set team_commission_locked = settings_row.team_commission_per_sale
     where o.team_commission_locked is null
       and lower(o.status) in ('payment_approved','paid','pagamento_aprovado');
  end if;
end $$;

alter table public.affiliate_orders enable row level security;

-- The application uses the server-side service role for these tables.
-- No client-side INSERT/SELECT policies are intentionally created.


create table if not exists public.affiliate_withdrawals (
  id bigint generated by default as identity primary key,
  affiliate_id bigint not null references public.affiliates(id) on delete cascade,
  pix_key text,
  amount numeric(12,2) not null check (amount > 0),
  status text not null default 'pending' check (status in ('pending','approved','paid','rejected','cancelled')),
  note text,
  requested_at timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists affiliate_withdrawals_affiliate_idx on public.affiliate_withdrawals(affiliate_id, requested_at desc);
alter table public.affiliate_withdrawals enable row level security;

-- Status administrativo separado do status operacional da afiliada.
-- Não interfere em login, links, checkout ou recebimento de comissão.
alter table public.affiliates
  add column if not exists admin_active boolean not null default true;

create index if not exists affiliates_admin_active_idx on public.affiliates(admin_active);

-- Histórico do status administrativo para permitir relatórios por mês.
-- Cada alteração manual ou automática registrada pelo sistema cria uma nova linha.
create table if not exists public.affiliate_admin_status_history (
  id bigint generated by default as identity primary key,
  affiliate_id bigint not null references public.affiliates(id) on delete cascade,
  admin_active boolean not null,
  effective_at timestamptz not null default now()
);

create index if not exists affiliate_admin_status_history_affiliate_idx
  on public.affiliate_admin_status_history(affiliate_id, effective_at desc);
alter table public.affiliate_admin_status_history enable row level security;


-- Dados de contato e recebimento da afiliada.
-- O WhatsApp é usado apenas para o contato administrativo.
-- O PIX atual pode ser substituído pela afiliada a qualquer momento.
alter table public.affiliates
  add column if not exists cpf text;

create unique index if not exists affiliates_cpf_unique_idx
  on public.affiliates(cpf)
  where cpf is not null;

alter table public.affiliates
  add column if not exists whatsapp text;

alter table public.affiliates
  add column if not exists pix_key text;

-- O PIX é copiado para cada solicitação no momento do saque.
-- Assim, trocar o PIX depois não altera saques antigos.
alter table public.affiliate_withdrawals
  add column if not exists pix_key text;

-- Configurações globais das comissões e da meta de ticket médio.
-- O registro id=1 é único e é alterado somente pelo painel administrativo.
create table if not exists public.affiliate_settings (
  id integer primary key check (id = 1),
  ticket_threshold numeric(12,2) not null default 170.00,
  ticket_bonus numeric(12,2) not null default 5.00,
  commission_none numeric(12,2) not null default 30.00,
  commission_bronze numeric(12,2) not null default 40.00,
  commission_silver numeric(12,2) not null default 50.00,
  commission_gold numeric(12,2) not null default 60.00,
  updated_at timestamptz not null default now()
);

insert into public.affiliate_settings (id)
values (1)
on conflict (id) do nothing;

alter table public.affiliate_settings enable row level security;


-- Rede de equipe de 1 nível. Cada afiliada pode ter uma única afiliada mãe.
-- Ao excluir a mãe, a filha permanece no sistema, mas fica sem equipe.
alter table public.affiliates
  add column if not exists team_parent_id bigint references public.affiliates(id) on delete set null;

-- Data/hora em que a afiliada entrou na equipe. Usada para conceder o Bronze
-- promocional somente no mês em que ela entrou.
alter table public.affiliates
  add column if not exists team_joined_at timestamptz;

create index if not exists affiliates_team_parent_idx on public.affiliates(team_parent_id);

-- Origem do saque: pessoal ou comissão de equipe.
alter table public.affiliate_withdrawals
  add column if not exists source text not null default 'personal';

update public.affiliate_withdrawals
set source = 'personal'
where source is null or source = '';

-- Comissão paga por cada venda de uma afiliada direta da equipe.
alter table public.affiliate_settings
  add column if not exists team_commission_per_sale numeric(12,2) not null default 10.00;


-- Código público permanente da equipe: 6 caracteres alfanuméricos,
-- único por afiliada e gerado uma única vez.
create or replace function public.generate_affiliate_team_code()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  candidate text;
begin
  loop
    candidate := '';
    for i in 1..6 loop
      candidate := candidate || substr('ABCDEFGHJKLMNPQRSTUVWXYZ23456789', floor(random() * 32 + 1)::int, 1);
    end loop;

    exit when not exists (
      select 1 from public.affiliates where team_code = candidate
    );
  end loop;
  return candidate;
end;
$$;

alter table public.affiliates
  add column if not exists team_code text;

alter table public.affiliates
  alter column team_code set default public.generate_affiliate_team_code();

update public.affiliates
set team_code = public.generate_affiliate_team_code()
where team_code is null or btrim(team_code) = '';

create unique index if not exists affiliates_team_code_unique_idx
  on public.affiliates(team_code);

alter table public.affiliates
  alter column team_code set not null;

-- Solicitações de divulgação de vídeos das afiliadas.
-- A afiliada envia apenas o link; a SHE decide se aprova ou rejeita a divulgação.
create table if not exists public.affiliate_video_submissions (
  id bigint generated by default as identity primary key,
  affiliate_id bigint not null references public.affiliates(id) on delete cascade,
  video_url text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  note text,
  terms_version text not null,
  terms_accepted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create index if not exists affiliate_video_submissions_affiliate_idx
  on public.affiliate_video_submissions(affiliate_id, created_at desc);
create index if not exists affiliate_video_submissions_status_idx
  on public.affiliate_video_submissions(status, created_at desc);
alter table public.affiliate_video_submissions enable row level security;
