-- SHE AFILIADAS
-- Execute este SQL no Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.affiliates (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique,
  name text not null,
  slug text unique,
  email text not null unique,
  cpf text,
  whatsapp text,
  pix_key text,
  active boolean not null default true,
  commission_rate numeric(6,4) not null default 0.1000,
  created_at timestamptz not null default now()
);

create table if not exists public.affiliate_events (
  id bigint generated by default as identity primary key,
  affiliate_id bigint not null references public.affiliates(id) on delete cascade,
  type text not null check (type in ('access','click')),
  target text,
  visitor_id text,
  path text,
  referrer text,
  event_key text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.affiliate_orders (
  id bigint generated by default as identity primary key,
  yampi_order_id text not null unique,
  affiliate_id bigint not null references public.affiliates(id) on delete cascade,
  status text not null default 'created',
  total numeric(12,2) not null default 0,
  commission numeric(12,2) not null default 0,
  raw_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists affiliate_events_affiliate_idx on public.affiliate_events(affiliate_id, created_at desc);
create index if not exists affiliate_orders_affiliate_idx on public.affiliate_orders(affiliate_id, created_at desc);
create index if not exists affiliate_orders_status_idx on public.affiliate_orders(status);

-- Snapshot da comissão aplicada à venda.
-- As vendas do mês atual usam a configuração vigente e podem ser recalculadas
-- retroativamente dentro do próprio mês quando o nível da afiliada muda.
-- Quando o mês termina, o campo commission fica congelado e meses anteriores
-- não são recalculados por alterações posteriores no painel.
alter table public.affiliate_orders
  add column if not exists commission_level_snapshot text,
  add column if not exists commission_base_snapshot numeric(12,2),
  add column if not exists team_commission_snapshot numeric(12,2);

create index if not exists affiliate_orders_commission_level_idx
  on public.affiliate_orders(affiliate_id, commission_level_snapshot);

alter table public.affiliates enable row level security;
alter table public.affiliate_events enable row level security;
alter table public.affiliate_orders enable row level security;

-- The application uses the server-side service role for these tables.
-- No client-side INSERT/SELECT policies are intentionally created.


create table if not exists public.affiliate_withdrawals (
  id bigint generated by default as identity primary key,
  affiliate_id bigint not null references public.affiliates(id) on delete cascade,
  pix_key text,
  amount numeric(12,2) not null check (amount > 0),
  status text not null default 'pending' check (status in ('pending','approved','paid','rejected','cancelled')),
  note text,
  requested_at timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists affiliate_withdrawals_affiliate_idx on public.affiliate_withdrawals(affiliate_id, requested_at desc);
alter table public.affiliate_withdrawals enable row level security;

-- Status administrativo separado do status operacional da afiliada.
-- Não interfere em login, links, checkout ou recebimento de comissão.
alter table public.affiliates
  add column if not exists admin_active boolean not null default true;

create index if not exists affiliates_admin_active_idx on public.affiliates(admin_active);

-- Histórico do status administrativo para permitir relatórios por mês.
-- Cada alteração manual ou automática registrada pelo sistema cria uma nova linha.
create table if not exists public.affiliate_admin_status_history (
  id bigint generated by default as identity primary key,
  affiliate_id bigint not null references public.affiliates(id) on delete cascade,
  admin_active boolean not null,
  effective_at timestamptz not null default now()
);

create index if not exists affiliate_admin_status_history_affiliate_idx
  on public.affiliate_admin_status_history(affiliate_id, effective_at desc);
alter table public.affiliate_admin_status_history enable row level security;


-- Dados de contato e recebimento da afiliada.
-- O WhatsApp é usado apenas para o contato administrativo.
-- O PIX atual pode ser substituído pela afiliada a qualquer momento.
alter table public.affiliates
  add column if not exists cpf text;

create unique index if not exists affiliates_cpf_unique_idx
  on public.affiliates(cpf)
  where cpf is not null;

alter table public.affiliates
  add column if not exists whatsapp text;

alter table public.affiliates
  add column if not exists pix_key text;

-- O PIX é copiado para cada solicitação no momento do saque.
-- Assim, trocar o PIX depois não altera saques antigos.
alter table public.affiliate_withdrawals
  add column if not exists pix_key text;

-- Configurações globais das comissões e da meta de ticket médio.
-- O registro id=1 é único e é alterado somente pelo painel administrativo.
create table if not exists public.affiliate_settings (
  id integer primary key check (id = 1),
  ticket_threshold numeric(12,2) not null default 170.00,
  ticket_bonus numeric(12,2) not null default 5.00,
  commission_none numeric(12,2) not null default 30.00,
  commission_bronze numeric(12,2) not null default 40.00,
  commission_silver numeric(12,2) not null default 50.00,
  commission_gold numeric(12,2) not null default 60.00,
  updated_at timestamptz not null default now()
);

insert into public.affiliate_settings (id)
values (1)
on conflict (id) do nothing;

alter table public.affiliate_settings enable row level security;


-- Rede de equipe de 1 nível. Cada afiliada pode ter uma única afiliada mãe.
-- Ao excluir a mãe, a filha permanece no sistema, mas fica sem equipe.
alter table public.affiliates
  add column if not exists team_parent_id bigint references public.affiliates(id) on delete set null;

-- Data/hora em que a afiliada entrou na equipe. Usada para conceder o Bronze
-- promocional somente no mês em que ela entrou.
alter table public.affiliates
  add column if not exists team_joined_at timestamptz;

create index if not exists affiliates_team_parent_idx on public.affiliates(team_parent_id);

-- Origem do saque: pessoal ou comissão de equipe.
alter table public.affiliate_withdrawals
  add column if not exists source text not null default 'personal';

update public.affiliate_withdrawals
set source = 'personal'
where source is null or source = '';

-- Comissão paga por cada venda de uma afiliada direta da equipe.
alter table public.affiliate_settings
  add column if not exists team_commission_per_sale numeric(12,2) not null default 10.00;


-- Código público permanente da equipe: 6 caracteres alfanuméricos,
-- único por afiliada e gerado uma única vez.
create or replace function public.generate_affiliate_team_code()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  candidate text;
begin
  loop
    candidate := '';
    for i in 1..6 loop
      candidate := candidate || substr('ABCDEFGHJKLMNPQRSTUVWXYZ23456789', floor(random() * 32 + 1)::int, 1);
    end loop;

    exit when not exists (
      select 1 from public.affiliates where team_code = candidate
    );
  end loop;
  return candidate;
end;
$$;

alter table public.affiliates
  add column if not exists team_code text;

alter table public.affiliates
  alter column team_code set default public.generate_affiliate_team_code();

update public.affiliates
set team_code = public.generate_affiliate_team_code()
where team_code is null or btrim(team_code) = '';

create unique index if not exists affiliates_team_code_unique_idx
  on public.affiliates(team_code);

alter table public.affiliates
  alter column team_code set not null;

-- Solicitações de divulgação de vídeos das afiliadas.
-- A afiliada envia apenas o link; a SHE decide se aprova ou rejeita a divulgação.
create table if not exists public.affiliate_video_submissions (
  id bigint generated by default as identity primary key,
  affiliate_id bigint not null references public.affiliates(id) on delete cascade,
  video_url text not null,
  status text not null default 'pending' check (status in ('pending', 'approved', 'rejected')),
  note text,
  terms_version text not null,
  terms_accepted_at timestamptz not null default now(),
  created_at timestamptz not null default now(),
  reviewed_at timestamptz
);

create index if not exists affiliate_video_submissions_affiliate_idx
  on public.affiliate_video_submissions(affiliate_id, created_at desc);
create index if not exists affiliate_video_submissions_status_idx
  on public.affiliate_video_submissions(status, created_at desc);
alter table public.affiliate_video_submissions enable row level security;

-- Permite que a conta seja criada antes da definição do link. O slug definitivo é criado dentro do painel como slug + ID.
alter table public.affiliates alter column slug drop not null;


-- Metas configuráveis dos dois sistemas de nível:
-- Bônus Mensal: vendas necessárias dentro do mês.
-- Bônus Fixo: vendas acumuladas que criam um piso permanente para o nível mensal.
alter table public.affiliate_settings
  add column if not exists monthly_bronze_sales integer not null default 10,
  add column if not exists monthly_silver_sales integer not null default 50,
  add column if not exists monthly_gold_sales integer not null default 101,
  add column if not exists fixed_bronze_sales integer not null default 100,
  add column if not exists fixed_silver_sales integer not null default 300,
  add column if not exists fixed_gold_sales integer not null default 500;

-- Sistema de Impulsionar Equipe
alter table public.affiliate_settings
  add column if not exists team_boost_small_price numeric(12,2) not null default 30.00,
  add column if not exists team_boost_small_connections integer not null default 5,
  add column if not exists team_boost_large_price numeric(12,2) not null default 50.00,
  add column if not exists team_boost_large_connections integer not null default 10,
  add column if not exists team_boost_max_active integer not null default 3;

alter table public.affiliates
  add column if not exists team_join_source text;

update public.affiliates
set team_join_source = 'organic'
where team_parent_id is not null and (team_join_source is null or team_join_source = '');

alter table public.affiliates
  drop constraint if exists affiliates_team_join_source_check;
alter table public.affiliates
  add constraint affiliates_team_join_source_check
  check (team_join_source is null or team_join_source in ('organic', 'boost'));

create table if not exists public.affiliate_team_boosts (
  id bigint generated by default as identity primary key,
  affiliate_id bigint not null references public.affiliates(id) on delete cascade,
  price numeric(12,2) not null check (price > 0),
  connections_total integer not null check (connections_total > 0),
  connections_remaining integer not null check (connections_remaining >= 0),
  status text not null default 'queued' check (status in ('queued','active','completed','cancelled')),
  queue_created_at timestamptz not null default now(),
  activated_at timestamptz,
  completed_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists affiliate_team_boosts_status_queue_idx
  on public.affiliate_team_boosts(status, queue_created_at asc);
create index if not exists affiliate_team_boosts_affiliate_idx
  on public.affiliate_team_boosts(affiliate_id, created_at desc);
alter table public.affiliate_team_boosts enable row level security;

create sequence if not exists public.team_boost_activation_seq;

alter table public.affiliate_team_boosts
  add column if not exists activation_order bigint;

create unique index if not exists affiliate_team_boosts_one_open_per_affiliate_idx
  on public.affiliate_team_boosts(affiliate_id)
  where status in ('queued','active');

create table if not exists public.affiliate_team_boost_reservations (
  id bigint generated by default as identity primary key,
  boost_id bigint not null references public.affiliate_team_boosts(id) on delete cascade,
  affiliate_id bigint not null references public.affiliates(id) on delete cascade,
  status text not null default 'reserved' check (status in ('reserved','consumed','expired')),
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  consumed_at timestamptz
);

create index if not exists affiliate_team_boost_reservations_boost_idx
  on public.affiliate_team_boost_reservations(boost_id, status, expires_at);
create unique index if not exists affiliate_team_boost_reservations_one_open_per_affiliate_idx
  on public.affiliate_team_boost_reservations(affiliate_id)
  where status = 'reserved';
alter table public.affiliate_team_boost_reservations enable row level security;

create table if not exists public.team_boost_distribution_state (
  id integer primary key check (id = 1),
  last_boost_id bigint references public.affiliate_team_boosts(id) on delete set null,
  updated_at timestamptz not null default now()
);
insert into public.team_boost_distribution_state (id)
values (1)
on conflict (id) do nothing;
alter table public.team_boost_distribution_state enable row level security;

create or replace function public.she_team_boost_activate_waiting()
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  max_active integer;
  active_count integer;
  next_boost record;
begin
  select team_boost_max_active into max_active from affiliate_settings where id = 1;
  max_active := greatest(coalesce(max_active, 3), 0);

  loop
    select count(*) into active_count from affiliate_team_boosts where status = 'active';
    exit when active_count >= max_active;

    select * into next_boost
    from affiliate_team_boosts
    where status = 'queued'
    order by queue_created_at asc, id asc
    limit 1
    for update skip locked;

    exit when not found;

    update affiliate_team_boosts
    set status = 'active', activated_at = now(), activation_order = nextval('team_boost_activation_seq')
    where id = next_boost.id;
  end loop;
end;
$$;

create or replace function public.she_team_boost_purchase(
  p_affiliate_id bigint,
  p_price numeric,
  p_connections integer,
  p_earned_balance numeric
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  existing record;
  reserved_amount numeric;
  personal_withdrawals numeric;
  available numeric;
  new_boost record;
begin
  perform pg_advisory_xact_lock(984512, p_affiliate_id::integer);

  select * into existing
  from affiliate_team_boosts
  where affiliate_id = p_affiliate_id and status in ('queued','active')
  limit 1;
  if found then
    raise exception 'Você já possui um impulso na fila ou ativo.' using errcode = 'P0001';
  end if;

  select coalesce(sum(amount),0) into personal_withdrawals
  from affiliate_withdrawals
  where affiliate_id = p_affiliate_id and source = 'personal' and status in ('pending','approved','paid');

  select coalesce(sum(price),0) into reserved_amount
  from affiliate_team_boosts
  where affiliate_id = p_affiliate_id and status in ('queued','active','completed');

  available := coalesce(p_earned_balance,0) - personal_withdrawals - reserved_amount;
  if available + 0.001 < p_price then
    raise exception 'Saldo disponível insuficiente para este impulso. Saldo: R$ %', round(available,2) using errcode = 'P0002';
  end if;

  insert into affiliate_team_boosts (affiliate_id, price, connections_total, connections_remaining, status)
  values (p_affiliate_id, p_price, p_connections, p_connections, 'queued')
  returning * into new_boost;

  perform she_team_boost_activate_waiting();

  select * into new_boost from affiliate_team_boosts where id = new_boost.id;
  return jsonb_build_object('boostId', new_boost.id, 'status', new_boost.status, 'price', new_boost.price, 'connections', new_boost.connections_total);
end;
$$;

create or replace function public.she_team_boost_find(p_affiliate_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  existing_reservation record;
  selected_boost record;
  state_last bigint;
  expiry timestamptz := now() + interval '15 minutes';
  reserved_count integer;
begin
  perform pg_advisory_xact_lock(984513, p_affiliate_id::integer);

  update affiliate_team_boost_reservations
  set status = 'expired'
  where status = 'reserved' and expires_at <= now();

  select * into existing_reservation
  from affiliate_team_boost_reservations
  where affiliate_id = p_affiliate_id and status = 'reserved' and expires_at > now()
  order by id desc limit 1;

  if found then
    select b.*, a.name as parent_name
    into selected_boost
    from affiliate_team_boosts b join affiliates a on a.id = b.affiliate_id
    where b.id = existing_reservation.boost_id;
    return jsonb_build_object('reservationId', existing_reservation.id, 'parentId', selected_boost.affiliate_id, 'parentName', selected_boost.parent_name, 'expiresAt', existing_reservation.expires_at);
  end if;

  perform she_team_boost_activate_waiting();

  select last_boost_id into state_last from team_boost_distribution_state where id = 1 for update;

  if state_last is null then
    select b.*, a.name as parent_name into selected_boost
    from affiliate_team_boosts b join affiliates a on a.id = b.affiliate_id
    where b.status = 'active' and b.connections_remaining > 0
      and b.connections_remaining > (select count(*) from affiliate_team_boost_reservations r where r.boost_id=b.id and r.status='reserved' and r.expires_at>now())
    order by b.activation_order asc nulls first, b.id asc limit 1;
  else
    select b.*, a.name as parent_name into selected_boost
    from affiliate_team_boosts b join affiliates a on a.id = b.affiliate_id
    where b.status = 'active' and b.connections_remaining > 0
      and b.connections_remaining > (select count(*) from affiliate_team_boost_reservations r where r.boost_id=b.id and r.status='reserved' and r.expires_at>now())
      and b.activation_order > (select coalesce(activation_order,0) from affiliate_team_boosts where id=state_last)
    order by b.activation_order asc limit 1;

    if not found then
      select b.*, a.name as parent_name into selected_boost
      from affiliate_team_boosts b join affiliates a on a.id = b.affiliate_id
      where b.status = 'active' and b.connections_remaining > 0
        and b.connections_remaining > (select count(*) from affiliate_team_boost_reservations r where r.boost_id=b.id and r.status='reserved' and r.expires_at>now())
      order by b.activation_order asc nulls first, b.id asc limit 1;
    end if;
  end if;

  if not found then
    raise exception 'No momento não há uma conexão disponível para encontrar equipe.' using errcode='P0003';
  end if;

  insert into affiliate_team_boost_reservations (boost_id, affiliate_id, expires_at)
  values (selected_boost.id, p_affiliate_id, expiry)
  returning id into existing_reservation;

  update team_boost_distribution_state set last_boost_id=selected_boost.id, updated_at=now() where id=1;

  return jsonb_build_object('reservationId', existing_reservation.id, 'parentId', selected_boost.affiliate_id, 'parentName', selected_boost.parent_name, 'expiresAt', expiry);
end;
$$;

create or replace function public.she_team_boost_confirm(
  p_affiliate_id bigint,
  p_reservation_id bigint
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  reservation record;
  boost record;
  child record;
  parent record;
  remaining integer;
begin
  perform pg_advisory_xact_lock(984514, p_affiliate_id::integer);

  select * into reservation from affiliate_team_boost_reservations
  where id=p_reservation_id and affiliate_id=p_affiliate_id and status='reserved'
  for update;
  if not found or reservation.expires_at <= now() then
    if found then update affiliate_team_boost_reservations set status='expired' where id=reservation.id; end if;
    raise exception 'A indicação de equipe expirou. Encontre uma nova equipe.' using errcode='P0004';
  end if;

  select * into child from affiliates where id=p_affiliate_id for update;
  if child.team_parent_id is not null then raise exception 'Você já está em uma equipe.' using errcode='P0005'; end if;
  if exists (select 1 from affiliate_orders where affiliate_id=p_affiliate_id and lower(status) in ('payment_approved','paid','pagamento_aprovado')) then
    raise exception 'A entrada em uma equipe só pode ser feita antes da primeira venda.' using errcode='P0006';
  end if;

  select * into boost from affiliate_team_boosts where id=reservation.boost_id for update;
  if boost.status <> 'active' or boost.connections_remaining <= 0 then raise exception 'Essa conexão não está mais disponível.' using errcode='P0007'; end if;

  select * into parent from affiliates where id=boost.affiliate_id and active=true;
  if not found then raise exception 'A afiliada mãe não está disponível.' using errcode='P0008'; end if;

  update affiliates set team_parent_id=parent.id, team_joined_at=now(), team_join_source='boost' where id=p_affiliate_id;
  update affiliate_team_boost_reservations set status='consumed', consumed_at=now() where id=reservation.id;
  remaining := boost.connections_remaining - 1;
  update affiliate_team_boosts
  set connections_remaining=remaining,
      status=case when remaining=0 then 'completed' else status end,
      completed_at=case when remaining=0 then now() else completed_at end
  where id=boost.id;

  if remaining=0 then perform she_team_boost_activate_waiting(); end if;

  return jsonb_build_object('affiliateId',p_affiliate_id,'parentId',parent.id,'parentName',parent.name,'parentWhatsapp',coalesce(parent.whatsapp,''),'boostId',boost.id,'connectionsRemaining',remaining);
end;
$$;

create or replace function public.she_team_boost_leave_queue(p_affiliate_id bigint)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  boost record;
begin
  perform pg_advisory_xact_lock(984515, p_affiliate_id::integer);
  select * into boost from affiliate_team_boosts where affiliate_id=p_affiliate_id and status='queued' order by id desc limit 1 for update;
  if not found then raise exception 'Você não possui um impulso aguardando na fila.' using errcode='P0009'; end if;
  update affiliate_team_boosts set status='cancelled', completed_at=now() where id=boost.id;
  perform she_team_boost_activate_waiting();
  return jsonb_build_object('boostId',boost.id,'refunded',boost.price);
end;
$$;

create or replace function public.she_team_boost_admin_state()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  active_count integer;
  queue_count integer;
  delivered integer;
  active_rows jsonb;
begin
  select count(*) into active_count from affiliate_team_boosts where status='active';
  select count(*) into queue_count from affiliate_team_boosts where status='queued';
  select count(*) into delivered from affiliate_team_boosts where status='completed';
  select coalesce(jsonb_agg(x order by x.activated_at asc), '[]'::jsonb) into active_rows
  from (
    select b.id,b.affiliate_id,a.name,a.whatsapp,b.price,b.connections_total,b.connections_remaining,b.status,b.queue_created_at,b.activated_at
    from affiliate_team_boosts b join affiliates a on a.id=b.affiliate_id
    where b.status='active'
    order by b.activated_at asc
  ) x;
  return jsonb_build_object('activeCount',active_count,'queueCount',queue_count,'completedCount',delivered,'active',active_rows);
end;
$$;


-- RPCs abaixo são chamadas somente pelo backend com a service role.
revoke execute on function public.she_team_boost_activate_waiting() from public, anon, authenticated;
revoke execute on function public.she_team_boost_purchase(bigint,numeric,integer,numeric) from public, anon, authenticated;
revoke execute on function public.she_team_boost_find(bigint) from public, anon, authenticated;
revoke execute on function public.she_team_boost_confirm(bigint,bigint) from public, anon, authenticated;
revoke execute on function public.she_team_boost_leave_queue(bigint) from public, anon, authenticated;
revoke execute on function public.she_team_boost_admin_state() from public, anon, authenticated;
grant execute on function public.she_team_boost_activate_waiting() to service_role;
grant execute on function public.she_team_boost_purchase(bigint,numeric,integer,numeric) to service_role;
grant execute on function public.she_team_boost_find(bigint) to service_role;
grant execute on function public.she_team_boost_confirm(bigint,bigint) to service_role;
grant execute on function public.she_team_boost_leave_queue(bigint) to service_role;
grant execute on function public.she_team_boost_admin_state() to service_role;
