-- SHE AFILIADAS
-- Execute este SQL no Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.affiliates (
  id bigint generated by default as identity primary key,
  auth_user_id uuid not null unique,
  name text not null,
  slug text not null unique,
  email text not null unique,
  whatsapp text,
  pix_key text,
  active boolean not null default true,
  commission_rate numeric(6,4) not null default 0.1000,
  created_at timestamptz not null default now()
);

create table if not exists public.affiliate_events (
  id bigint generated by default as identity primary key,
  affiliate_id bigint not null references public.affiliates(id) on delete cascade,
  type text not null check (type in ('access','click')),
  target text,
  visitor_id text,
  path text,
  referrer text,
  event_key text not null unique,
  created_at timestamptz not null default now()
);

create table if not exists public.affiliate_orders (
  id bigint generated by default as identity primary key,
  yampi_order_id text not null unique,
  affiliate_id bigint not null references public.affiliates(id) on delete cascade,
  status text not null default 'created',
  total numeric(12,2) not null default 0,
  commission numeric(12,2) not null default 0,
  raw_payload jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists affiliate_events_affiliate_idx on public.affiliate_events(affiliate_id, created_at desc);
create index if not exists affiliate_orders_affiliate_idx on public.affiliate_orders(affiliate_id, created_at desc);
create index if not exists affiliate_orders_status_idx on public.affiliate_orders(status);

alter table public.affiliates enable row level security;
alter table public.affiliate_events enable row level security;
alter table public.affiliate_orders enable row level security;

-- The application uses the server-side service role for these tables.
-- No client-side INSERT/SELECT policies are intentionally created.


create table if not exists public.affiliate_withdrawals (
  id bigint generated by default as identity primary key,
  affiliate_id bigint not null references public.affiliates(id) on delete cascade,
  pix_key text,
  amount numeric(12,2) not null check (amount > 0),
  status text not null default 'pending' check (status in ('pending','approved','paid','rejected','cancelled')),
  note text,
  requested_at timestamptz not null default now(),
  processed_at timestamptz
);

create index if not exists affiliate_withdrawals_affiliate_idx on public.affiliate_withdrawals(affiliate_id, requested_at desc);
alter table public.affiliate_withdrawals enable row level security;

-- Status administrativo separado do status operacional da afiliada.
-- Não interfere em login, links, checkout ou recebimento de comissão.
alter table public.affiliates
  add column if not exists admin_active boolean not null default true;

create index if not exists affiliates_admin_active_idx on public.affiliates(admin_active);

-- Histórico do status administrativo para permitir relatórios por mês.
-- Cada alteração manual ou automática registrada pelo sistema cria uma nova linha.
create table if not exists public.affiliate_admin_status_history (
  id bigint generated by default as identity primary key,
  affiliate_id bigint not null references public.affiliates(id) on delete cascade,
  admin_active boolean not null,
  effective_at timestamptz not null default now()
);

create index if not exists affiliate_admin_status_history_affiliate_idx
  on public.affiliate_admin_status_history(affiliate_id, effective_at desc);
alter table public.affiliate_admin_status_history enable row level security;


-- Dados de contato e recebimento da afiliada.
-- O WhatsApp é usado apenas para o contato administrativo.
-- O PIX atual pode ser substituído pela afiliada a qualquer momento.
alter table public.affiliates
  add column if not exists whatsapp text;

alter table public.affiliates
  add column if not exists pix_key text;

-- O PIX é copiado para cada solicitação no momento do saque.
-- Assim, trocar o PIX depois não altera saques antigos.
alter table public.affiliate_withdrawals
  add column if not exists pix_key text;

-- Configurações globais das comissões e da meta de ticket médio.
-- O registro id=1 é único e é alterado somente pelo painel administrativo.
create table if not exists public.affiliate_settings (
  id integer primary key check (id = 1),
  ticket_threshold numeric(12,2) not null default 170.00,
  ticket_bonus numeric(12,2) not null default 5.00,
  commission_none numeric(12,2) not null default 30.00,
  commission_bronze numeric(12,2) not null default 40.00,
  commission_silver numeric(12,2) not null default 50.00,
  commission_gold numeric(12,2) not null default 60.00,
  updated_at timestamptz not null default now()
);

insert into public.affiliate_settings (id)
values (1)
on conflict (id) do nothing;

alter table public.affiliate_settings enable row level security;
